### ISSUE TITLE
error making: ros-noetic-rosgraph-msgs

### ISSUE THREAD

**Issue by guntursiboro** [ros-noetic-arch/ros-noetic-rosgraph-msgs#1]
I am trying to install ros-noetic-desktop-full 1.5.0-1, but terminated because of
`error making: ros-noetic-rosgraph-msgs`

So I spesifically install this package to find out more, I use this command in terminal
`yay -S ros-noetic-rosgraph-msgs --rebuildtree &| tee ros-noetic-rosgraph-msgs.txt`

and here is the output that I get.
`[Aur:1]  ros-noetic-rosgraph-msgs-1.11.3-1

  1 ros-noetic-rosgraph-msgs                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> :: [1mDeleting (1/1): /home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs[0m
:: [1mDownloaded PKGBUILD (1/1): ros-noetic-rosgraph-msgs[0m
  1 ros-noetic-rosgraph-msgs                 (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> :: [1m(1/1) Parsing SRCINFO: ros-noetic-rosgraph-msgs[0m
==> Making package: ros-noetic-rosgraph-msgs 1.11.3-1 (Sab 10 Apr 2021 02:35:58 )
==> Retrieving sources...
  -> Downloading ros-noetic-rosgraph-msgs-1.11.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   125  100   125    0     0    117      0  0:00:01  0:00:01 --:--:--   117

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  2483    0  2483    0     0   1143      0 --:--:--  0:00:02 --:--:--  2549
==> Validating source files with sha256sums...
    ros-noetic-rosgraph-msgs-1.11.3.tar.gz ... Passed
==> Making package: ros-noetic-rosgraph-msgs 1.11.3-1 (Sab 10 Apr 2021 02:36:01 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ros-noetic-rosgraph-msgs-1.11.3.tar.gz
==> Validating source files with sha256sums...
    ros-noetic-rosgraph-msgs-1.11.3.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting ros-noetic-rosgraph-msgs-1.11.3.tar.gz with bsdtar
==> Sources are ready.
==> Making package: ros-noetic-rosgraph-msgs 1.11.3-1 (Sab 10 Apr 2021 02:36:02 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python (found suitable version "3.9.2", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.9/site-packages/em.py  
-- Using empy: /usr/lib/python3.9/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
CMake Warning at /usr/src/gmock/CMakeLists.txt:43 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Deprecation Warning at /usr/src/gmock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning at /usr/src/googletest/CMakeLists.txt:54 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Deprecation Warning at /usr/src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found PythonInterp: /usr/bin/python (found version "3.9.2") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-3.9
-- catkin 0.8.8
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'ModuleNotFoundError'>: No module named 'genmsg'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/em.py", line 3303, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib/python3.9/site-packages/em.py", line 3301, in main
    invoke(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/em.py", line 3284, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/lib/python3.9/site-packages/em.py", line 2295, in wrap
    self.fail(e)
  File "/usr/lib/python3.9/site-packages/em.py", line 2284, in wrap
    callable(*args)
  File "/usr/lib/python3.9/site-packages/em.py", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/lib/python3.9/site-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib/python3.9/site-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib/python3.9/site-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib/python3.9/site-packages/em.py", line 2596, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'genmsg'
CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  
  execute_process(/home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/catkin_generated/env_cached.sh
  "/usr/bin/python" "/usr/lib/python3.9/site-packages/em.py" "--raw-errors"
  "-F"
  "/home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/cmake/rosgraph_msgs-genmsg-context.py"
  "-o"
  "/home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/cmake/rosgraph_msgs-genmsg.cmake"
  "/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/noetic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:12 (generate_messages)

-- Configuring incomplete, errors occurred!
See also "/home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/thunderel05/.cache/yay/ros-noetic-rosgraph-msgs/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
error making: ros-noetic-rosgraph-msgs`

Thanks in advanced for you help.

**Comment by guntursiboro** [comment]
How do you uninstall all ros-noetic-* packages? I tried to uninstall using comman below, but it didn't do anything. 
`sudo pacman -Rsu ros-noetic*`
It said 
`No matches for wildcard “ros-noetic*”. See `help expand`.
sudo pacman -Rsu ros-noetic*`

**Comment by HarrisonDuffield** [comment]
I also am facing the same issue. I have followed the above steps, checked the environment paths are inplace. Don't seem to be getting any further. Will let you know if I get anywhere

**Comment by AchmadFathoni** [comment]
I never touch arch4edu, but If I were you I will try install `ros-noetic-genmsg` manually by
```
yay -S ros-noetic-genmsg --asdeps
```
and then install the complete ROS
```
yay -S ros-noetic-desktop-full
```

**Comment by AchmadFathoni** [comment]
What command do you use to install ros anyway?

**Comment by HarrisonDuffield** [comment]
> What command do you use to install ros anyway?

I'm on mobile at the moment but it is the one on their website, should be something like 


`yay -S ros-noetic-desktop-full`

**Comment by acxz** [comment]
I just tried installing this and was able to do so. Closing this issue under lack of activity. Please feel free to comment on this if you are still experiencing errors.

**Comment by klaasg** [comment]
Hi, I was getting this error too.
It worked after running the following solution above:

> Go to `~/.cache/yay/ros-noetic-genmsg` and then run `makepkg -fiC`

Now, however, I'm getting the same error for `ros-noetic-gencpp`:
```
ModuleNotFoundError: No module named 'gencpp'
```

EDIT:
After this, I had to reinstall several `ros-noetic-gen*` packages untill this package would finally compile.
